name: CorevanTim
version: '${project.version}'
main: me.megamagnum.main.Main
api-version: 1.19
authors: [ MegaMagnum ]
description: Temporary lifesteal type of beat
commands:
  withdraw:
    description: Withdraw a heart!
  random:
    description: Geeft een random nummer
    usage: /<command> (maximale nummer)
  afk:
    description: retard als je dit niet snapt
  meme:
    description: meme
  kleur:
    description: Kies de kleur van je sterretje
    usage: /<command> <kleur>
  giveheart:
    description: Geef hartjes aan een speler (alleen console)
    usage: /<command> <speler> <aantal>
  removeheart:
    description: Verwijder hartjes van een speler (alleen console)
    usage: /<command> <speler> <aantal>
  performance:
    description: Bekijk server performance en TPS
    usage: /<command>
    aliases: [servertps, tps, ping, lag]
  ai:
    description: Vraag de AI complottheorie generator
    usage: /<command> <vraag>
  triggerevent:
    description: Trigger een random challenge event (alleen console)
    usage: /<command>
  reverse:
    description: Reverse speler movement (alleen console)
    usage: /<command> [speler] [seconden]
  mycoords:
    description: Laat je coördinaten zien met Nether/Overworld conversie
    usage: /<command>
    aliases: [coords, coordinates, whereami]