name: CorevanTim
version: '${project.version}'
main: me.megamagnum.main.Main
api-version: 1.19
authors: [ MegaMagnum ]
description: Temporary lifesteal type of beat
commands:
  withdraw:
    description: Withdraw a heart!
  random:
    description: Geeft een random nummer
    usage: /<command> (maximale nummer)
  performance:
    description: Dedotated Wam?
  afk:
    description: retard als je dit niet snapt
  meme:
    description: meme